// Banco de preguntas por clase — Cálculo II. Autocorregido.
window.QUIZZES_II = {
"1": {
  "titulo": "¿Entendiste el límite ε–δ?",
  "qs": [
    { "q": "En la definición ε–δ de límite, ¿quién \"juega\" primero y quién responde?", "opts": ["Primero se elige δ y después se busca un ε que funcione", "Primero el desafío: dado cualquier ε > 0, hay que conseguir un δ > 0 que lo garantice", "ε y δ se eligen a la vez, sin importar el orden"], "ok": 1, "fb": "El orden es esencial: primero el adversario fija la tolerancia ε > 0, y recién entonces uno debe exhibir un δ > 0 que la cumpla. Que δ pueda depender de ε es justamente la gracia." },
    { "q": "¿Qué significa exactamente \"0 < |x − a| < δ ⇒ |f(x) − L| < ε\"?", "opts": ["Si x está a menos de δ de a (sin ser a), entonces f(x) está a menos de ε de L", "Si f(x) está cerca de L, entonces x está cerca de a", "El valor f(a) debe ser igual a L"], "ok": 0, "fb": "La definición controla la salida (|f(x) − L| < ε) a partir de la entrada (0 < |x − a| < δ). El 0 < excluye a x = a: el límite no mira qué pasa en a, solo alrededor." },
    { "q": "¿Por qué Weierstrass reemplazó \"acercarse tanto como uno quiera\" por desigualdades?", "opts": ["Porque las desigualdades son más fáciles de calcular", "Porque \"acercarse\" sugiere movimiento e infinitesimales, ideas que nadie sabía definir; las desigualdades evitan los \"fantasmas\"", "Porque el límite en realidad no existe"], "ok": 1, "fb": "La definición ε–δ habla de lo infinitamente cercano sin mencionar infinito ni movimiento: solo dos desigualdades y un orden. Así se eliminan los \"fantasmas de cantidades difuntas\" que denunciaba Berkeley." },
    { "q": "Una IA \"demostró con ε–δ\" que lím_(x→2) (3x−1) = 5 diciendo: «Cuando x tiende a 2, 3x tiende a 6, así que 3x−1 tiende a 5». ¿Es una demostración ε–δ válida?", "opts": ["Sí: el resultado es 5 y el razonamiento es correcto", "No: el resultado es correcto, pero es circular y no exhibe ningún δ", "No: el resultado está mal, el límite no es 5", "Sí, porque menciona ε y δ en algún momento"], "ok": 1, "fb": "El 5 está bien, pero la \"prueba\" es circular: usa «tiende a», que es justo lo que la definición viene a fundamentar. Una demostración real exhibe el δ: dado ε > 0, con δ = ε/3 se tiene |(3x−1)−5| = 3|x−2| < 3δ = ε." }
  ]
},
"2": {
  "titulo": "¿Captaste qué es una función continua?",
  "qs": [
    { "q": "Según la definición precisa, ¿qué tres cosas exige que f sea continua en a?", "opts": ["Solo que f esté definida en a", "Que el límite en a exista, que f(a) exista, y que coincidan", "Que f no tenga saltos en ningún punto del dominio"], "ok": 1, "fb": "Continua en a ⟺ lím_(x→a) f(x) = f(a). Eso pide tres cosas a la vez: que el límite exista, que f(a) exista y que sean iguales. Si falla cualquiera, hay discontinuidad." },
    { "q": "Si el límite en a existe pero f no está definida ahí (o vale otra cosa), ¿qué tipo de rotura es?", "opts": ["Un salto", "Una discontinuidad evitable (agujero)", "Una asíntota (discontinuidad esencial)", "No es una discontinuidad: la función igual es continua"], "ok": 1, "fb": "Cuando el límite existe pero f(a) no está definida o difiere, es una discontinuidad evitable: se puede \"tapar el agujero\" redefiniendo f(a) como ese límite." },
    { "q": "Weierstrass (1872) construyó una función continua en todos los puntos pero derivable en ninguno. ¿Qué muestra ese ejemplo?", "opts": ["Que la metáfora del \"dibujar sin levantar el lápiz\" capta toda la sutileza de la continuidad", "Que la continuidad es más sutil que \"no tener cortes\": se puede ser continuo y a la vez infinitamente rugoso", "Que esa función en realidad no es continua"], "ok": 1, "fb": "La función de Weierstrass es continua (no tiene cortes) pero todo picos, imposible de trazar a mano. Rompe la idea ingenua de que continuo = suave o dibujable: la continuidad es más sutil que la metáfora del lápiz." },
    { "q": "Una IA afirma: «f(x)=1/x es discontinua en x=0 porque ahí no está definida y los límites laterales tienden a −∞ y +∞». ¿Cómo la auditarías?", "opts": ["Está bien: es una discontinuidad esencial/asintótica, y el límite no existe", "Está mal: en realidad es una discontinuidad evitable", "Está mal: 1/x es continua en 0"], "ok": 0, "fb": "Es correcta: 0 no está en el dominio y el límite no existe (laterales infinitos de distinto signo), así que es esencial/asintótica, NO evitable. Auditar también es confirmar lo correcto y exigir el nombre exacto: llamarla \"evitable\" sí sería un error." }
  ]
},
"3": {
  "titulo": "¿Te quedó claro Bolzano?",
  "qs": [
    { "q": "¿Qué afirma el teorema de Bolzano?", "opts": ["Toda función con un valor negativo y uno positivo tiene una raíz entre ellos", "Si f es continua en [a,b] y f(a)·f(b) < 0, entonces existe c ∈ (a,b) con f(c) = 0", "Una función continua siempre tiene una raíz"], "ok": 1, "fb": "Bolzano necesita dos hipótesis: continuidad en [a,b] y cambio de signo (f(a)·f(b) < 0). Recién ahí garantiza una raíz interior. Sin continuidad el resultado se cae." },
    { "q": "La demostración de Bolzano (partir el intervalo, quedarse con la mitad donde sigue habiendo cambio de signo, repetir) es famosa porque...", "opts": ["es la única forma de probar el teorema", "no es solo una prueba: es el método de bisección para encontrar raíces", "no usa la continuidad de la función"], "ok": 1, "fb": "Bolzano quería probar lo \"obvio\" sin dibujos y de paso inventó un algoritmo: la bisección acorrala el cero en intervalos que se achican a la mitad. Hoy lo usan las calculadoras." },
    { "q": "Del teorema de Bolzano se obtiene el teorema del valor intermedio, que dice que una función continua...", "opts": ["alcanza todos los valores entre f(a) y f(b)", "es siempre positiva entre a y b", "tiene un máximo entre a y b"], "ok": 0, "fb": "El valor intermedio generaliza Bolzano: si f es continua, alcanza cualquier valor entre f(a) y f(b), no solo el 0. (El caso del 0 es Bolzano: cambio de signo ⇒ raíz.)" },
    { "q": "Una IA afirma: «Toda función que vale −3 en un punto y +5 en otro tiene una raíz entre ellos, por el valor intermedio». ¿Es correcto el enunciado?", "opts": ["Sí, siempre tiene una raíz", "No: le falta la hipótesis de continuidad", "No: el valor intermedio no dice nada sobre raíces", "Sí, porque −3 y +5 tienen distinto signo"], "ok": 1, "fb": "Le borra la hipótesis CLAVE: la continuidad. Funciones como ⌊x⌋−2,5 o 1/x cambian de signo sin tener raíz entre medio. Error típico: enunciar un teorema correcto pero sin sus hipótesis, que es donde está toda la matemática." }
  ]
},
"4": {
  "titulo": "¿Por qué el máximo existe (Weierstrass)?",
  "qs": [
    { "q": "¿Qué garantiza el teorema de los valores extremos (Weierstrass)?", "opts": ["Que toda función continua tiene máximo y mínimo", "Que una función continua en un intervalo cerrado y acotado alcanza un máximo y un mínimo absolutos ahí", "Que toda función acotada alcanza su supremo", "Que toda función definida en un intervalo abierto tiene máximo"], "ok": 1, "fb": "Las tres condiciones —continua, cerrado y acotado— son todas necesarias. Recién con las tres se garantiza que el máximo y el mínimo se alcanzan de verdad (no solo se aproximan)." },
    { "q": "¿Por qué f(x)=x no tiene máximo en el intervalo abierto (0,1)?", "opts": ["Porque no es continua", "Porque el supremo 1 no pertenece al intervalo: se acerca a 1 pero nunca lo alcanza", "Porque no está acotada"], "ok": 1, "fb": "El intervalo abierto rompe la hipótesis \"cerrado\". El supremo es 1, pero 1 ∉ (0,1), así que no es máximo: no hay punto donde la función lo alcance." },
    { "q": "El teorema de Weierstrass es importante para el Eje de la derivada porque...", "opts": ["permite calcular derivadas más rápido", "garantiza que un problema de optimización TIENE solución antes de salir a buscarla", "demuestra que toda función es derivable"], "ok": 1, "fb": "Es el \"permiso para optimizar\": asegura que el máximo y el mínimo existen. Sin él, uno podría pasarse la vida buscando un máximo que no existe." },
    { "q": "Una IA dice: «f(x)=x no tiene máximo en (0,1): el supremo es 1, pero no se alcanza porque 1 ∉ (0,1)». ¿Cómo la auditás?", "opts": ["Está bien razonado: distingue supremo de máximo e identifica que falla la hipótesis de cerrado", "Está mal: el máximo es 1", "Está mal: la función no es continua, así que el teorema no aplica"], "ok": 0, "fb": "Correcto: el supremo (1) existe pero no es máximo porque 1 ∉ (0,1); el intervalo abierto rompe la hipótesis de Weierstrass. Auditar acá es confirmar y nombrar con precisión la diferencia entre supremo (cota mínima) y máximo (valor alcanzado)." }
  ]
},
"5": {
  "titulo": "¿Qué es de verdad la recta tangente?",
  "qs": [
    { "q": "¿Por qué un solo punto P no alcanza para fijar la recta tangente?", "opts": ["Porque por un punto pasan infinitas rectas: falta la dirección", "Porque la tangente no pasa por P", "Porque P tiene que estar fuera de la curva"], "ok": 0, "fb": "Por un punto pasan infinitas rectas; hace falta una segunda información: la dirección. Por eso se usa un segundo punto Q y se lo desliza hacia P." },
    { "q": "¿Cómo se define la pendiente de la tangente a y = f(x) en P(a, f(a))?", "opts": ["Como f(a) dividido por a", "Como m = lím_(h→0) (f(a+h) − f(a)) / h, la posición límite de las secantes", "Como la recta que toca la curva en un solo punto"], "ok": 1, "fb": "La secante por P y Q = (a+h, f(a+h)) tiene pendiente (f(a+h)−f(a))/h. Al hacer h → 0, la secante gira hasta la tangente: ese límite es la pendiente." },
    { "q": "El método de Fermat (≈1636) para la tangente \"incomodaba\" porque...", "opts": ["dividía por una cantidad E y después la hacía cero, como un \"fantasma\"", "no daba la pendiente correcta", "necesitaba calculadoras"], "ok": 0, "fb": "Fermat dividía por E y luego lo \"borraba\" poniéndolo en cero. La idea era correcta (la tangente como límite de secantes), pero sin el límite parecía manipular \"fantasmas de cantidades difuntas\", como denunció después Berkeley." },
    { "q": "Una IA define la tangente como «la recta que toca a la curva en un solo punto sin cruzarla». ¿Es una buena definición general?", "opts": ["Sí, sirve para cualquier curva", "No: falla en general (en y=x³ la tangente cruza en el origen; y=1 toca a y=sen x en infinitos puntos siendo tangente)", "No: la tangente nunca toca la curva", "Sí, porque funciona para la circunferencia"], "ok": 1, "fb": "Esa definición vale solo para círculos y curvas convexas. La tangente a y=x³ en el origen CRUZA la curva; y=1 toca a y=sen x en infinitos puntos siendo tangente. La definición correcta es el límite de secantes, no \"tocar en un punto\"." }
  ]
},
"6": {
  "titulo": "¿Qué mide la velocidad instantánea?",
  "qs": [
    { "q": "¿Por qué \"velocidad en un instante\" parece un sinsentido al principio?", "opts": ["Porque en un instante no transcurre tiempo: velocidad = distancia/tiempo daría 0/0", "Porque la velocidad no se puede medir", "Porque la flecha de Zenón nunca se mueve"], "ok": 0, "fb": "En un único instante Δt = 0, así que distancia/tiempo da 0/0, indefinido. La salida es calcular velocidades medias en intervalos cada vez más cortos y ver a qué número se acercan." },
    { "q": "¿Cómo se define la velocidad instantánea v(t) a partir de la posición s(t)?", "opts": ["Como s(t) dividido por t", "Como v(t) = lím_(Δt→0) (s(t+Δt) − s(t)) / Δt", "Como la velocidad media en todo el recorrido"], "ok": 1, "fb": "La velocidad media en [t, t+Δt] es (s(t+Δt)−s(t))/Δt; la instantánea es su límite cuando Δt → 0. Es un límite de cocientes bien definido, no un 0/0." },
    { "q": "¿Qué descubrimiento conecta el problema de Newton (velocidad) con el de Fermat (tangente)?", "opts": ["Que son problemas totalmente distintos", "Que la velocidad instantánea es el MISMO límite que la pendiente de la tangente al gráfico de s(t)", "Que la velocidad media siempre es cero"], "ok": 1, "fb": "La velocidad media es la pendiente de una secante sobre el gráfico de s(t), y la instantánea es la pendiente de la tangente. El problema físico de Newton y el geométrico de Fermat eran el mismo límite." },
    { "q": "Una IA calcula la velocidad instantánea en t=2 de s(t)=t² así: «como en t=2 no pasa tiempo, hacemos s(2)/2 = 4/2 = 2 m/s». Auditá el procedimiento.", "opts": ["Está bien: la velocidad instantánea es 2 m/s", "Está mal: confunde \"posición sobre tiempo total\" con el límite del cociente incremental; lo correcto es 4 m/s", "Está mal en el número pero bien en el método", "Está bien: en un instante no pasa tiempo, así que hay que dividir s(2) por 2"], "ok": 1, "fb": "Doble error: concepto y cuenta. s(2)/2 es la media desde el reposo en [0,2] (2 m/s), no la instantánea. Lo correcto es v(2)=lím_(Δt→0)((2+Δt)²−4)/Δt = lím_(Δt→0)(4+Δt) = 4 m/s." }
  ]
},
"7": {
  "titulo": "¿Por qué no rehacemos el límite cada vez que derivamos?",
  "qs": [
    { "q": "Según la idea central de la clase, ¿qué relación hay entre la definición de derivada y las reglas de derivación?", "opts": ["Las reglas son una herramienta distinta que reemplaza por completo a la noción de límite", "Las reglas encapsulan el límite del cociente incremental, que costó dos mil años de pensamiento, para no rehacerlo cada vez", "La definición por límite vale solo para polinomios y las reglas para el resto"], "ok": 1, "fb": "La derivada se define como f′(a)=lím_(h→0)(f(a+h)−f(a))/h; las reglas (xⁿ→n·xⁿ⁻¹, suma, producto…) son ese límite ya destilado en álgebra. La cuenta es cómoda, pero la idea sigue siendo el límite." },
    { "q": "La derivada en un punto a se interpreta a la vez como…", "opts": ["pendiente de la tangente y velocidad instantánea: una sola idea con dos caras", "área bajo la curva y velocidad promedio", "pendiente de la secante y aceleración"], "ok": 0, "fb": "El límite del cociente incremental es simultáneamente la pendiente de la tangente (Fermat) y la velocidad instantánea (Galileo). Newton y Leibniz vieron que eran un único límite." },
    { "q": "¿Cuál de estas reglas básicas está bien escrita?", "opts": ["(f·g)′ = f′·g′", "(f/g)′ = (f′·g + f·g′)/g²", "(c·f)′ = c·f′ y (f+g)′ = f′+g′"], "ok": 2, "fb": "La derivada respeta sumas y constantes: (f+g)′=f′+g′ y (c·f)′=c·f′. En cambio el producto NO se reparte ((f·g)′=f′·g+f·g′) y el cociente lleva una resta en el numerador." },
    { "q": "Una IA derivó f(x)=x²·sen(x) afirmando: «la derivada de un producto es el producto de las derivadas, así que f′(x)=2x·cos(x)». ¿Es válida?", "opts": ["Sí, derivar arriba y abajo siempre funciona en productos", "No: inventó una regla falsa; la del producto es (f·g)′=f′·g+f·g′, así que f′(x)=2x·sen(x)+x²·cos(x)", "Sí, porque (x²)′=2x y (sen x)′=cos x son correctas por separado"], "ok": 1, "fb": "El error clásico: (f·g)′ NO es f′·g′. La regla correcta da f′(x)=2x·sen(x)+x²·cos(x). Comprobalo con f=g=x: (x²)′=2x, pero 1·1=1; no coinciden." }
  ]
},
"8": {
  "titulo": "¿Qué le dice la segunda derivada a la forma de la curva?",
  "qs": [
    { "q": "¿Cuál es la lectura geométrica central de la primera y la segunda derivada?", "opts": ["f′ dice si sube o baja (pendiente); f′′ dice cómo se curva (concavidad)", "f′ mide el área; f′′ mide la pendiente", "f′ y f′′ dicen lo mismo, solo cambia la notación"], "ok": 0, "fb": "La primera derivada indica crecimiento/decrecimiento (pendiente); la segunda indica concavidad: f′′>0 cóncava hacia arriba (⌣), f′′<0 cóncava hacia abajo (⌢). Eso permite dibujar la función." },
    { "q": "En física, si f es la posición, ¿qué representan f′ y f′′?", "opts": ["f′ es la aceleración y f′′ la velocidad", "f′ es la velocidad y f′′ es la aceleración", "ambas son la velocidad en distintas unidades"], "ok": 1, "fb": "f′ es la velocidad (tasa de cambio de la posición) y f′′ es la aceleración (tasa de cambio de la velocidad). La ley de Newton F=m·a está escrita en la segunda derivada." },
    { "q": "Para f(x)=x³ se tiene f′′(x)=6x, que cambia de signo en x=0. ¿Qué hay ahí?", "opts": ["Un máximo, porque f′(0)=0", "Un punto de inflexión: cambia la concavidad", "Una discontinuidad de la curva"], "ok": 1, "fb": "Donde f′′ cambia de signo hay punto de inflexión: la concavidad pasa de ⌢ a ⌣. En x³ es además creciente a ambos lados (f′=3x²≥0), así que no es extremo." },
    { "q": "Una IA dice que f(x)=x³ tiene un punto de inflexión en x=0 y que ahí NO hay máximo ni mínimo, aunque f′(0)=0, porque f′′=6x cambia de signo y f′=3x²≥0 siempre. ¿Es válida?", "opts": ["Sí: cambia la concavidad y f es creciente a ambos lados, así que es inflexión y no extremo", "No: si f′(0)=0 siempre hay máximo o mínimo", "No: x³ no tiene puntos críticos"], "ok": 0, "fb": "Correcto y bien razonado: f′′=6x cambia de signo (inflexión) y f′=3x²≥0 no cambia de signo, así que no hay extremo. Desarma el error «f′(c)=0 ⇒ extremo»: es condición necesaria, no suficiente." }
  ]
},
"9": {
  "titulo": "¿En algún instante fuiste exactamente al promedio?",
  "qs": [
    { "q": "¿Qué afirma el teorema del valor medio (Lagrange)?", "opts": ["Si f es continua en [a,b] y derivable en (a,b), existe c∈(a,b) con f′(c)=(f(b)−f(a))/(b−a)", "Toda función continua alcanza su promedio en el punto medio del intervalo", "La derivada de una función continua siempre es constante"], "ok": 0, "fb": "El teorema garantiza un punto interior c donde la tangente tiene la misma pendiente que la secante de los extremos: la velocidad instantánea iguala a la promedio." },
    { "q": "El teorema de Rolle es el caso particular del valor medio cuando…", "opts": ["f no es derivable en ningún punto", "f(a)=f(b): la secante es horizontal y existe c con f′(c)=0", "el intervalo es infinito"], "ok": 1, "fb": "Si f(a)=f(b) la secante tiene pendiente 0, así que en el medio hay un punto con tangente horizontal (f′(c)=0): un máximo o mínimo interior. Rolle lo probó en 1691." },
    { "q": "¿Por qué este teorema es «el pilar oculto del cálculo»?", "opts": ["Porque permite calcular cualquier integral directamente", "Porque de él se deducen «derivada cero ⇒ función constante», los criterios de crecimiento y es una llave del Teorema Fundamental", "Porque reemplaza a la definición de derivada"], "ok": 1, "fb": "Es el puente formal entre lo promedio y lo instantáneo: de él salen los criterios de crecimiento y es una de las llaves del Teorema Fundamental del Cálculo." },
    { "q": "Una IA aplica el valor medio a f(x)=|x| en [−1,1]: dice que la secante tiene pendiente 0 y que existe c=0 con f′(0)=0, así que el teorema se cumple. ¿Es válida?", "opts": ["Sí, porque el mínimo está en 0 y el numerito da 0", "No: |x| no es derivable en x=0, así que no cumple las hipótesis y el teorema no se le puede aplicar", "Sí, porque |x| es continua en [−1,1]"], "ok": 1, "fb": "El razonamiento es inválido: f(x)=|x| no es derivable en 0 (hay un pico), f′(0) ni existe. Sin la hipótesis de derivabilidad en (−1,1), el teorema no aplica, aunque el número final parezca razonable." }
  ]
},
"10": {
  "titulo": "Cuando 0/0 no quiere decir nada… todavía",
  "qs": [
    { "q": "Según la idea central, ¿qué significa que al reemplazar quede la forma 0/0?", "opts": ["Que el límite no existe ni tiene respuesta posible", "Que es una indeterminación: numerador y denominador tienden a cero a la vez y falta ver «cuál gana la carrera»", "Que el resultado es siempre 1"], "ok": 1, "fb": "0/0 no es una respuesta sino una pregunta abierta: el resultado depende de cómo cada parte tiende a cero. La misma definición de derivada es un 0/0 legítimo." },
    { "q": "¿Cuál es la hipótesis NO negociable para aplicar la regla de L'Hôpital?", "opts": ["Que el límite sea de la forma 0/0 o ∞/∞", "Que la función sea un polinomio", "Que el punto sea x=0"], "ok": 0, "fb": "L'Hôpital exige la forma 0/0 o ∞/∞. Otras indeterminadas (0·∞, ∞−∞, 0⁰, 1^∞, ∞⁰) hay que llevarlas primero a esas formas con álgebra o logaritmos." },
    { "q": "¿Cuál es la intuición geométrica detrás de la regla de L'Hôpital?", "opts": ["El área bajo f sobre el área bajo g tiende a 1", "Cerca del punto cada función se parece a su recta tangente, así que la razón f/g se acerca a la razón de pendientes f′/g′", "El cociente de dos funciones siempre vale su derivada"], "ok": 1, "fb": "Cerca de a, f y g se confunden con sus tangentes; si ambas pasan por cero, el cociente f/g se comporta como f′/g′. De ahí lím f/g = lím f′/g′ bajo hipótesis." },
    { "q": "Una IA resolvió lím_(x→0)(x²+3x)/(x+1) aplicando L'Hôpital: derivó arriba y abajo y dio (2x+3)/1=3. ¿Es válida?", "opts": ["Sí, derivar arriba y abajo siempre es correcto en cocientes", "No: en x=0 queda 0/1, que no es indeterminada; no corresponde L'Hôpital y el límite real es 0", "Sí, porque el 3 es un número prolijo"], "ok": 1, "fb": "Al reemplazar x=0 queda 0/1=0, que NO es 0/0 ni ∞/∞. L'Hôpital no aplica; el límite se obtiene por sustitución y vale 0, no 3. Aplicó la regla fuera de hipótesis y hasta erró el número." }
  ]
},
"11": {
  "titulo": "¿Hasta dónde podemos confiar en la tangente?",
  "qs": [
    { "q": "¿Qué es la linealización de f en un punto a?", "opts": ["La recta tangente L(x)=f(a)+f′(a)·(x−a), usada como aproximación f(x)≈L(x) cerca de a", "El promedio de f en todo el intervalo", "La segunda derivada evaluada en a"], "ok": 0, "fb": "La tangente L(x)=f(a)+f′(a)(x−a) es la mejor aproximación de primer grado: cerca de a la curva y la recta casi se confunden, así que f(x)≈L(x)." },
    { "q": "La aproximación sen θ ≈ θ que usa la física del péndulo es, en el fondo…", "opts": ["una coincidencia sin explicación", "una aproximación lineal de sen θ en θ=0, válida solo para ángulos chicos", "una identidad exacta para todo θ"], "ok": 1, "fb": "Es la linealización de sen θ en 0 (su tangente es y=θ). Funciona por un ratito: cerca del punto la función y su tangente casi coinciden; lejos, el error crece." },
    { "q": "¿Por qué se dice que la tangente es la mejor aproximación de PRIMER grado?", "opts": ["Porque el error Δy−dy tiende a 0 más rápido que Δx cuando Δx→0", "Porque nunca comete error, ni lejos del punto", "Porque dy es siempre mayor que Δy"], "ok": 0, "fb": "Con dy=f′(x)dx, el error entre el cambio real Δy y el predicho dy tiende a 0 más rápido que el propio Δx. Por eso la recta es óptima entre las aproximaciones lineales… pero solo localmente." },
    { "q": "Una IA estimó √(4,1) con a=4: f(4)=2, f′(4)=1/4, L(x)=2+(1/4)(x−4), y dio L(4,1)=2,025. ¿Es válida?", "opts": ["Sí, y la justificación está completa", "Sí: el punto base, f′(4) y el cálculo están bien (real ≈2,0248); aunque faltó decir que por ser √x cóncava la estimación queda por encima del valor real", "No: a=4 está mal elegido"], "ok": 1, "fb": "El procedimiento y el número (2,025; real 2,0248…) son correctos. Lo que faltó: como √x es cóncava (f′′<0), la tangente queda por arriba de la curva, así que 2,025 es una leve sobreestimación." }
  ]
},
"12": {
  "titulo": "¿Cómo encuentra la derivada lo mejor posible sin probar todo?",
  "qs": [
    { "q": "¿Cuál es la condición de Fermat, corazón de la optimización?", "opts": ["En un extremo local interior donde f es derivable, f′(c)=0", "El máximo siempre está en los extremos del dominio", "f′′ debe valer cero en el óptimo"], "ok": 0, "fb": "Fermat notó que en un máximo o mínimo la cantidad casi no cambia ante variaciones chicas: su razón de cambio se anula. En un extremo interior derivable, f′(c)=0." },
    { "q": "En el método de optimización, ¿qué se hace tras escribir la función objetivo en una sola variable y hallar los puntos críticos?", "opts": ["Se acepta el primer punto crítico como respuesta", "Se clasifican los críticos y se evalúa TAMBIÉN en los extremos del dominio: el óptimo absoluto puede estar en la frontera", "Se descarta el dominio porque no influye"], "ok": 1, "fb": "El máximo o mínimo absoluto puede estar en un punto crítico O en la frontera del dominio admisible. Por eso hay que clasificar (1ª o 2ª derivada) y evaluar también en los extremos." },
    { "q": "¿Por qué fue un avance el aporte de Fermat (hacia 1630) frente a la geometría caso por caso?", "opts": ["Porque dio un método universal: escribir la cantidad, derivar, igualar a cero y analizar candidatos, sin un truco distinto por figura", "Porque calculaba áreas sin derivar", "Porque solo servía para la caja de cartón"], "ok": 0, "fb": "Antes cada figura pedía un ingenio geométrico propio. La derivada igualada a cero volvió el procedimiento universal: sirve igual para la caja, el corral, la lata o la ventana." },
    { "q": "Una IA resolvió el corral (100 m de alambre, área máxima): y=50−x, A(x)=50x−x², A′=50−2x=0 ⇒ x=25, y como A′′=−2<0 es máximo; da un cuadrado de 25×25 (625 m²). ¿Es válida?", "opts": ["No: el área máxima de un rectángulo nunca es un cuadrado", "Sí: usó bien la restricción, el punto crítico y la segunda derivada; conviene además mencionar el dominio 0<x<50 (el máximo cae en el interior)", "No: olvidó derivar"], "ok": 1, "fb": "Correcto y bien justificado: restricción 2x+2y=100, A(x)=50x−x², x=25 por A′=0 y A′′=−2<0 confirma máximo; cuadrado de 625 m². Solo faltó nombrar el dominio admisible 0<x<50." }
  ]
},
"13": {
  "titulo": "¿Qué te dicen f′ y f″ sobre la forma de una curva?",
  "qs": [
    { "q": "En el estudio completo de funciones, ¿qué información aporta el signo de la PRIMERA derivada f′?", "opts": ["La concavidad: si la curva es cóncava hacia arriba o hacia abajo", "El crecimiento: dónde la función sube y dónde baja, y dónde tiene extremos", "Las asíntotas verticales y horizontales de la curva"], "ok": 1, "fb": "f′ gobierna el crecimiento y los extremos: donde f′>0 la función crece, donde f′<0 decrece, y en los cambios de signo hay máximos o mínimos locales. La concavidad la dicta f″." },
    { "q": "Para f(x)=x³−3x se tiene f″(x)=6x. ¿Qué pasa en x=0?", "opts": ["Hay un máximo local, porque f″ se anula", "Hay un punto de inflexión, porque f″ cambia de signo (de − a +)", "Hay un mínimo local, porque la curva deja de bajar"], "ok": 1, "fb": "En x=0, f″ pasa de negativa (cóncava hacia abajo) a positiva (cóncava hacia arriba): es un punto de inflexión, un cambio de concavidad, no un extremo." },
    { "q": "¿Por qué un punto de inflexión NO es lo mismo que un máximo o un mínimo?", "opts": ["Porque la inflexión marca un cambio de concavidad (lo dicta f″), mientras que un extremo marca un cambio de crecimiento (lo dicta f′)", "Porque en la inflexión la función siempre vale cero", "Porque la inflexión solo aparece en funciones sin asíntotas"], "ok": 0, "fb": "El extremo es un cambio en cómo sube/baja la curva (signo de f′); la inflexión es un cambio de hacia dónde se curva (signo de f″). Son gestos independientes." },
    { "q": "Una IA respondió: «Para f(x)=x³−3x, como f″(−1)=−6<0 hay un mínimo local en x=−1, y como f″(1)=6>0 hay un máximo local en x=1.» ¿Es válida?", "opts": ["Sí, aplicó correctamente el criterio de la segunda derivada", "No: invirtió el criterio; f″<0 da máximo y f″>0 da mínimo, así que es al revés", "No, porque el criterio de la segunda derivada no sirve para clasificar extremos"], "ok": 1, "fb": "La IA aplicó el criterio al revés: si f″(c)<0 la curva es cóncava hacia abajo y hay MÁXIMO; si f″(c)>0 es cóncava hacia arriba y hay MÍNIMO. Lo correcto es máximo en x=−1 y mínimo en x=1." }
  ]
},
"14": {
  "titulo": "¿Cómo se mide el área de una región de borde curvo?",
  "qs": [
    { "q": "¿Cuál es la idea central para medir el área bajo una curva, heredada de Eudoxo y Arquímedes?", "opts": ["Buscar una fórmula geométrica directa para cada borde curvo", "Aproximar la región con rectángulos (piezas rectas) y apretar la aproximación hasta atrapar el área entre una cota inferior y una superior", "Tabular cientos de puntos de la curva y unirlos a mano"], "ok": 1, "fb": "El método de exhausción aproxima lo curvo con piezas rectas conocidas y aprieta cotas inferior y superior que se juntan; el límite lo vuelve una máquina general." },
    { "q": "Para una función creciente, ¿qué relación hay entre la suma por extremos izquierdos Lₙ, el área A y la suma por extremos derechos Rₙ?", "opts": ["Lₙ ≤ A ≤ Rₙ: la izquierda subestima y la derecha sobrestima", "Rₙ ≤ A ≤ Lₙ: la derecha subestima y la izquierda sobrestima", "Lₙ = Rₙ = A para cualquier cantidad de rectángulos"], "ok": 0, "fb": "Si f crece, los rectángulos por la izquierda quedan por debajo de la curva (subestiman) y los de la derecha sobresalen (sobrestiman): Lₙ ≤ A ≤ Rₙ, y ambas cotas se aprietan al aumentar n." },
    { "q": "¿Por qué el método de exhausción NO es simplemente «sumar infinitos términos»?", "opts": ["Porque en realidad usa solo un rectángulo muy grande", "Porque se trata de agotar la diferencia entre la figura y el polígono hasta hacerla menor que cualquier magnitud dada, sin invocar el infinito", "Porque los griegos sí conocían y usaban la idea moderna de límite"], "ok": 1, "fb": "Eudoxo no «llegaba al infinito»: restaba más de la mitad de la diferencia una y otra vez hasta que lo que quedaba fuera menor que cualquier magnitud prefijada. Es agotar la diferencia, no sumar infinitos términos." },
    { "q": "Una IA calculó R₄=15/32≈0,469 para el área bajo y=x² en [0,1] y concluyó: «como la función es creciente, ese valor es el área exacta». ¿Es válida?", "opts": ["Sí, R₄ da el área exacta cuando la función crece", "No: R₄ es una sobrestimación; el área exacta es el límite cuando n→∞, que vale 1/3", "No, porque el cálculo de R₄ está mal hecho"], "ok": 1, "fb": "El cálculo de R₄ (15/32) está bien, pero confundió una aproximación finita con el valor exacto. Como f crece, R₄>A; el área verdadera es el límite, 1/3≈0,333." }
  ]
},
"15": {
  "titulo": "¿Cómo volver definición precisa el «aproximar con rectángulos»?",
  "qs": [
    { "q": "¿En qué consiste la libertad esencial de la suma de Riemann frente a las sumas anteriores?", "opts": ["Exige siempre rectángulos de igual ancho y altura por el extremo izquierdo", "Permite particiones de anchos cualesquiera y un punto de muestra cualquiera dentro de cada subintervalo", "Solo funciona si la función es creciente y positiva"], "ok": 1, "fb": "Riemann soltó las muletas: ni los anchos tienen que ser iguales ni la altura se toma en un extremo fijo. Cualquier punto de muestra en cada franja sirve." },
    { "q": "¿Qué significa que una función f sea integrable según Riemann?", "opts": ["Que el límite de las sumas existe y da el MISMO número para toda partición y toda elección de puntos de muestra cuando la norma ‖P‖→0", "Que la suma de Riemann da el área geométrica solo con extremos derechos", "Que f es positiva y continua en todo el intervalo"], "ok": 0, "fb": "f es integrable si lím_(‖P‖→0) Σ f(xᵢ*)·Δxᵢ existe y coincide para toda partición y todo punto de muestra. Esa independencia de la elección es lo que la blinda contra trampas." },
    { "q": "Si en parte del intervalo f es negativa, ¿cómo aporta ese tramo a la suma de Riemann?", "opts": ["Aporta en valor absoluto, siempre sumando área positiva", "Aporta con signo negativo: el rectángulo bajo el eje resta", "No aporta nada, porque solo cuentan los tramos positivos"], "ok": 1, "fb": "La suma de Riemann mide área CON SIGNO: donde f<0, el rectángulo queda por debajo del eje y cuenta en negativo. Por eso deja de importar que la función crezca o baje." },
    { "q": "Una IA calculó la suma de Riemann R₆=0,875 para f(x)=x²−2x en [0,3] y concluyó: «como es positiva, el área entre la curva y el eje en [0,3] es 0,875». ¿Es válida?", "opts": ["Sí, la suma positiva da directamente el área geométrica", "No: 0,875 es el área NETA con signo (en [0,2] f es negativa y resta), no el área geométrica total", "No, porque la aritmética de la suma está mal hecha"], "ok": 1, "fb": "La aritmética está bien (R₆=0,875), pero confundió área neta con signo y área geométrica total. En [0,2] f<0 y resta; el área geométrica sería la suma de los valores absolutos, no el resultado neto." }
  ]
},
"16": {
  "titulo": "Si el límite de las sumas existe, ¿qué objeto es ∫?",
  "qs": [
    { "q": "¿Qué tipo de objeto matemático es la integral definida ∫_a^b f(x) dx?", "opts": ["Una función de x", "Un número fijo, atado al intervalo [a,b] y a la función f (la x es muda)", "Una familia de funciones que difieren en una constante"], "ok": 1, "fb": "La integral definida es un NÚMERO, no una función: el límite común de las sumas de Riemann. La variable de integración es muda; se podría llamar t sin cambiar el valor." },
    { "q": "Según las propiedades de la integral, ¿a qué equivale ∫_a^b [f+g] dx?", "opts": ["∫_a^b f · ∫_a^b g", "∫_a^b f + ∫_a^b g (linealidad)", "(∫_a^b f) / (∫_a^b g)"], "ok": 1, "fb": "Por linealidad, la integral de una suma es la suma de las integrales: ∫[f+g] = ∫f + ∫g, y ∫c·f = c·∫f. Son propiedades demostrables desde la definición como límite." },
    { "q": "Si f cambia de signo en [a,b], ¿qué representa geométricamente ∫_a^b f(x) dx?", "opts": ["El área geométrica total, sumando todo en valor absoluto", "El área con signo: lo que está sobre el eje suma y lo que está debajo resta", "Siempre cero, porque las partes se cancelan"], "ok": 1, "fb": "La integral es el área CON SIGNO: la parte sobre el eje aporta positivo y la parte bajo el eje aporta negativo. No es el área geométrica total (que sumaría los valores absolutos)." },
    { "q": "Una IA evaluó ∫ desde −1 hasta 2 de (1−x) dx como diferencia de áreas: triángulo sobre el eje (área 2) menos triángulo bajo el eje (área 1/2), dando 3/2. ¿Es válida?", "opts": ["Sí: 3/2 es el valor exacto y la lectura como área con signo es la adecuada", "No, porque debió sumar ambas áreas y dar 5/2", "No, porque la recta no cruza el eje en ese intervalo"], "ok": 0, "fb": "Correcto: la recta corta el eje en x=1, la parte de arriba (área 2) suma y la de abajo (área 1/2) resta, dando el área neta con signo 3/2. (El área geométrica total sería 5/2.)" }
  ]
},
"17": {
  "titulo": "¿Por qué derivar e integrar son la misma pregunta al revés?",
  "qs": [
    { "q": "¿Qué afirma la parte 1 del Teorema Fundamental sobre la función de acumulación A(x)=∫_a^x f(t) dt?", "opts": ["Que A(x)=f(b)−f(a)", "Que A es derivable y A′(x)=f(x): derivar la acumulación devuelve el integrando", "Que A(x) es siempre constante"], "ok": 1, "fb": "La parte 1 dice que la rapidez con que se acumula el área en x es exactamente la altura f(x): A′(x)=f(x). Derivar la función de acumulación recupera el integrando." },
    { "q": "Según la parte 2 (regla de Barrow), si F es cualquier antiderivada de f, ¿cuánto vale ∫_a^b f(x) dx?", "opts": ["F(b)−F(a)", "F′(b)−F′(a)", "F(a)·F(b)"], "ok": 0, "fb": "La regla de Barrow convierte el área en una resta: ∫_a^b f = F(b)−F(a). Acumular los cambios instantáneos de F desde a hasta b recupera su cambio total." },
    { "q": "¿En qué sentido «derivar e integrar son procesos inversos», la respuesta a la pregunta del año?", "opts": ["En que ambos dan siempre el mismo número", "En que si acumulás los cambios instantáneos de una cantidad desde a hasta b, recuperás su cambio total: medir el cambio y medir la acumulación son la misma pregunta dada vuelta", "En que ninguno de los dos se puede calcular sin tablas"], "ok": 1, "fb": "La derivada mide cómo cambia algo; la integral, cuánto se acumula. El TFC dice que acumular los cambios instantáneos reconstruye el cambio total: son operaciones inversas." },
    { "q": "Una IA derivó g(x)=∫_0^(x²) sen(t) dt y respondió g′(x)=sen(x²), reemplazando el límite superior. ¿Es válida?", "opts": ["Sí, basta reemplazar x por x² en el integrando", "No: olvidó la regla de la cadena; como el límite superior es u=x², falta el factor 2x y g′(x)=2x·sen(x²)", "No, porque la parte 1 del TFC no se aplica a funciones trigonométricas"], "ok": 1, "fb": "La parte 1 da la derivada directa solo cuando el límite superior es x. Acá es u=x², así que hay que componer con la cadena: g′(x)=sen(x²)·2x. Faltaba el factor 2x." }
  ]
},
"18": {
  "titulo": "¿Cómo se recorre la derivada al revés?",
  "qs": [
    { "q": "¿Por qué la integral indefinida se escribe como una familia ∫ f(x) dx = F(x) + C?", "opts": ["Porque derivar tiene infinitos resultados", "Porque la derivada de una constante es 0, así que (F+C)′=f para cualquier C: hay infinitas antiderivadas", "Porque el +C corrige errores de signo"], "ok": 1, "fb": "Antiderivar tiene infinitas respuestas: como la derivada de una constante es 0, si F′=f también (F+C)′=f. Por eso la antiderivada general es una familia F+C." },
    { "q": "¿De qué regla de derivación es «la inversa» la regla de sustitución?", "opts": ["De la regla del producto", "De la regla de la cadena: reconoce la derivada interna g′(x) escondida y cambia de variable", "De la regla del cociente"], "ok": 1, "fb": "La sustitución es la regla de la cadena leída al revés: ∫ f(g(x))·g′(x) dx = ∫ f(u) du. Hay que reconocer el factor g′(x) y cambiar de variable (y los límites, si es definida)." },
    { "q": "Según la honestidad del «al revés», ¿en qué se diferencia integrar de derivar?", "opts": ["En nada: ambos son procedimientos mecánicos", "En que derivar es mecánico (toda función elemental tiene derivada elemental), pero integrar no: hay funciones como e^(−x²) sin antiderivada elemental", "En que integrar es siempre más fácil que derivar"], "ok": 1, "fb": "Derivar es un algoritmo ciego; integrar es un arte de reconocimiento. Liouville (≈1835) probó que e^(−x²), por ejemplo, no tiene antiderivada elemental." },
    { "q": "Una IA resolvió ∫₀² 2x·(x²+1)² dx escribiendo «du/dx=2x», dejando los límites 0 y 2 y evaluando F(x)=(x²+1)³/3 entre ellos para dar 124/3. ¿Es válida?", "opts": ["Sí, el resultado 124/3 es correcto y el procedimiento también", "No: el resultado es correcto por casualidad, pero el procedimiento es inválido (no absorbió el dx ni cambió los límites a u; dos errores se compensaron)", "No, porque el resultado 124/3 está mal"], "ok": 1, "fb": "El número 124/3 está bien, pero por accidente: la IA trató el dx como decorativo (no despejó du=2x dx) y dejó límites en x evaluando la primitiva en x. Lo correcto es du=2x dx, límites u(0)=1, u(2)=5, ∫₁⁵ u² du=124/3." }
  ]
},
"19": {
  "titulo": "¿Cómo se pasa del área plana al volumen?",
  "qs": [
    { "q": "Para el área encerrada entre dos curvas f y g con f(x) ≥ g(x) en [a,b], ¿qué integral la calcula?", "opts": ["∫ₐᵇ [f(x) − g(x)] dx, la de arriba menos la de abajo", "∫ₐᵇ [f(x) + g(x)] dx, sumando ambas alturas", "∫ₐᵇ f(x)·g(x) dx, el producto de las curvas"], "ok": 0, "fb": "Cada rectángulo vertical de aproximación tiene altura f(x) − g(x) (la de arriba menos la de abajo) y ancho Δx; la integral acumula esas alturas. Si las curvas se cruzan, se parte el intervalo cuidando el signo." },
    { "q": "¿Cuál es la idea central que une el área entre curvas, los discos/arandelas y los cascarones cilíndricos?", "opts": ["Identificar la rebanada típica, escribir su medida y dejar que la integral la acumule", "Memorizar una fórmula distinta e independiente para cada tipo de sólido", "Que solo los sólidos de revolución se pueden medir con integrales"], "ok": 0, "fb": "Es una sola estrategia con varias caras: reconocer la rebanada (rectángulo, disco, arandela o cascarón), escribir su área o grosor, y acumular con la integral. Es la suma de Riemann llevada al espacio." },
    { "q": "Un mismo sólido de revolución se calcula por discos y por cascarones y da el mismo volumen. ¿Por qué no es casualidad?", "opts": ["Por el principio de Cavalieri: si las secciones tienen igual área, el volumen es el mismo, sin importar cómo se rebane", "Porque discos y cascarones siempre se usan sobre el eje x", "Porque el volumen depende del método elegido para rebanar"], "ok": 0, "fb": "El principio de Cavalieri (1635) garantiza que el volumen es la acumulación de las áreas de las secciones; por eso dos rebanados distintos del mismo cuerpo, bien planteados, llegan al mismo número. La elección de método es estratégica, no obligatoria." },
    { "q": "Una IA respondió: «Giro y = √x (con y = 0, de x = 0 a 4) alrededor del eje x; uso discos de radio √x, área π·(√x)² = π·x, así V = π·∫₀⁴ x dx = 8π». ¿Es válida?", "opts": ["Sí: el sólido es de revolución, el disco macizo tiene radio √x y V = π·(16/2) = 8π", "No, porque (√x)² no es igual a x", "No, porque debería haber usado cascarones y dar otro número"], "ok": 0, "fb": "El resultado y el planteo son correctos: disco de radio √x, área π·x, y V = 8π. Las rebanadas son perpendiculares al eje x y la región toca el eje (g = 0), por eso es disco macizo y no arandela; (√x)² = x vale porque x ≥ 0 en [0,4]. Auditar también es confirmar lo correcto y exigir el vocabulario." }
  ]
},
"20": {
  "titulo": "Si tengo la tasa, ¿cómo recupero el total?",
  "qs": [
    { "q": "¿Qué afirma el Teorema del Cambio Neto?", "opts": ["Si f es la tasa de cambio de una magnitud, ∫ₐᵇ f(x) dx es el cambio neto de esa magnitud en [a,b]", "La integral de una tasa siempre da la cantidad total bruta recorrida", "El cambio total solo se puede calcular si la tasa es constante"], "ok": 0, "fb": "Como F' = f es la tasa, ∫ₐᵇ f dx = F(b) − F(a): la integral de una razón de cambio es el cambio neto acumulado. Es el TFC leído como aplicación física." },
    { "q": "Si v(t) es la velocidad y a veces es negativa, ¿qué calcula ∫ₐᵇ v(t) dt frente a ∫ₐᵇ |v(t)| dt?", "opts": ["∫ v da el desplazamiento (cambio neto de posición); ∫ |v| da la distancia total recorrida", "Ambas dan exactamente lo mismo siempre", "∫ v da la distancia total y ∫ |v| el desplazamiento"], "ok": 0, "fb": "Cuando la tasa cambia de signo, la integral simple da el cambio NETO (desplazamiento); para la distancia total hay que integrar el valor absoluto. Distinguir cambio neto de cantidad bruta es un criterio que ninguna máquina decide sola." },
    { "q": "Para la función de acumulación A(x) = ∫ₐˣ f(t) dt, ¿qué relación hay entre A y f?", "opts": ["A'(x) = f(x): la acumulación, derivada, devuelve la tasa; A crece donde f > 0 y decrece donde f < 0", "A(x) siempre es igual a f(x)", "A no tiene relación con f porque la integral borra la información"], "ok": 0, "fb": "Esa es la cara «acumulación» del TFC: A'(x) = f(x). A crece donde f es positiva, decrece donde es negativa y se queda quieta donde f vale 0. Deja ver por qué derivar e integrar son inversas." },
    { "q": "Una IA respondió: «Para v(t) = t² − 2t − 8 en [1,6], la distancia total es ∫₁⁶ v dt = −10/3 m». ¿Es válida?", "opts": ["No: una distancia no puede ser negativa, y además confundió distancia con desplazamiento (faltó integrar |v|)", "Sí, el cálculo de la integral está bien hecho", "No, pero solo porque se equivocó en la aritmética de la primitiva"], "ok": 0, "fb": "Doble error: una distancia negativa es imposible (debió prender la alarma), y confundió distancia con desplazamiento. Como v = (t−4)(t+2) cambia de signo en t = 4, la distancia es ∫₁⁴ −v + ∫₄⁶ v = 98/3 ≈ 32,67 m. El −10/3 es el desplazamiento, ni siquiera lo que se le pidió." }
  ]
},
"21": {
  "titulo": "¿Qué significa «tender a» sin llegar nunca?",
  "qs": [
    { "q": "¿Qué quiere decir, con precisión, que lím aₙ = L?", "opts": ["Para todo ε > 0 existe N tal que si n ≥ N entonces |aₙ − L| < ε", "Que algún término aₙ es exactamente igual a L", "Que los términos crecen sin parar hacia L"], "ok": 0, "fb": "Converger no es llegar: es poder hacer los términos tan próximos a L como se quiera (dentro de cualquier ε) con tal de avanzar lo suficiente (a partir de un N). aₙ = 1/n nunca vale 0, pero 0 es su límite." },
    { "q": "La sucesión 3; 3,1; 3,14; 3,141; … se «aprieta» entre sí pero su límite es π. ¿Qué muestra esto?", "opts": ["Es de Cauchy pero no converge dentro de ℚ; converge en ℝ porque ℝ es completo (no tiene agujeros)", "Que el criterio de Cauchy nunca sirve para nada", "Que π es en realidad un número racional"], "ok": 0, "fb": "El criterio de Cauchy (términos que se aprietan entre sí) garantiza convergencia en ℝ, pero falla en ℚ: ahí π es un agujero. La completitud de ℝ, construida por Cantor y Dedekind, es lo que hace funcionar el cálculo." },
    { "q": "¿Para qué sirve el criterio de Cauchy, según la idea central de la clase?", "opts": ["Para afirmar que una sucesión converge sin conocer de antemano su límite", "Para calcular siempre el valor exacto del límite", "Para demostrar que toda sucesión acotada converge sin más"], "ok": 0, "fb": "Lo profundo de Cauchy es poder garantizar que un proceso se estabiliza sin nombrar su destino: si los términos se aprietan entre sí, en ℝ hay límite. Es el corazón de todo método numérico y del «converge» del machine learning." },
    { "q": "Una IA afirmó: «aₙ = (−1)ⁿ·(1/n) converge a 0 porque toda sucesión alternante converge a 0». ¿Es válida?", "opts": ["No: el límite 0 es correcto, pero el razonamiento es una regla inventada (aₙ = (−1)ⁿ es alternante y no converge)", "Sí, el razonamiento sobre sucesiones alternantes es correcto", "No, porque el límite en realidad no es 0"], "ok": 0, "fb": "El número final está bien, pero la justificación es inválida: es falso que «toda alternante converge a 0» (basta (−1)ⁿ). Lo correcto es por compresión: −1/n ≤ aₙ ≤ 1/n y ambas cotas → 0. Auditar es detectar la regla inventada aunque el resultado coincida." }
  ]
},
"22": {
  "titulo": "¿Una función entera escondida en sus derivadas?",
  "qs": [
    { "q": "¿Cómo se define la suma de una serie infinita, y cuánto vale ½ + ¼ + ⅛ + … ?", "opts": ["Es el límite de las sumas parciales; como sₙ = 1 − (1/2)ⁿ → 1, la suma es 1", "Es imposible: infinitos términos nunca dan un total finito", "Es el promedio de todos los términos sumados"], "ok": 0, "fb": "Sumar infinito = mirar si la sucesión de sumas parciales converge. Para la geométrica sₙ = 1 − (1/2)ⁿ → 1, así que la suma es 1: la paradoja de Zenón se disuelve. En general Σ a·rⁿ con |r| < 1 suma a/(1 − r)." },
    { "q": "¿Qué información de f usa el polinomio de Taylor Tₙ(x) = Σ f⁽ᵏ⁾(a)·(x−a)ᵏ/k! y por qué?", "opts": ["Las derivadas sucesivas en a: valor, pendiente, curvatura, etc.; con todas se reconstruye la función cerca de a", "Solo el valor de f en un punto, sin sus derivadas", "Los valores de f en infinitos puntos distintos"], "ok": 0, "fb": "Cada derivada en a aporta una capa de información geométrica (valor, pendiente, curvatura…). Por eso dos funciones con las mismas derivadas en a tienen el mismo Taylor ahí, y por eso la calculadora evalúa eˣ, sen x, cos x sumando potencias." },
    { "q": "Al subir el grado del polinomio de Taylor de f en a, ¿qué ocurre con la aproximación?", "opts": ["Abraza cada vez mejor a la curva alrededor de a; si Tₙ(x) → f(x), se obtiene la serie de Taylor", "Empeora siempre porque agrega más error", "Solo sirve para polinomios, no para eˣ o sen x"], "ok": 0, "fb": "La recta tangente aproxima un poco, el término cuadrático mejora, y así sucesivamente: cada derivada suma un término y ensancha el intervalo de buen ajuste. Cuando Tₙ → f dentro del radio de convergencia, se escribe la serie." },
    { "q": "Una IA afirmó: «Σ 1/n converge porque sus términos 1/n tienden a 0». ¿Es válida?", "opts": ["No: que el término general → 0 es necesario pero no suficiente; la serie armónica diverge", "Sí, si los términos tienden a 0 la suma siempre es finita", "No, porque 1/n no tiende a 0"], "ok": 0, "fb": "Error clásico de confundir condición necesaria con suficiente. La armónica diverge: agrupando, 1/3+1/4 > 1/2, 1/5+…+1/8 > 1/2, infinitas veces (Oresme, ~1350). Por la misma lógica de la IA «convergería» Σ 1/√n, que tampoco lo hace." }
  ]
},
"23": {
  "titulo": "Sin fórmula, ¿cómo hallamos la raíz?",
  "qs": [
    { "q": "¿Cuál es la idea central para resolver f(x) = 0 cuando no hay fórmula?", "opts": ["Acorralar la raíz con una sucesión de aproximaciones que converja a ella, controlando el error", "Buscar siempre una fórmula por radicales aunque sea de grado alto", "Adivinar un valor y comprobar si es exacto"], "ok": 0, "fb": "Galois (1832) probó que de grado ≥ 5 no hay fórmula general por radicales: si no hay fórmula, hay que aproximar con una sucesión que converja, y el verdadero contenido es controlar el error y decidir cuándo parar." },
    { "q": "¿Qué distingue a la bisección del método de Newton?", "opts": ["Bisección es segura pero lenta (error ≤ (b−a)/2ⁿ); Newton es rápido (cuadrático) pero puede divergir", "Newton siempre es seguro y bisección siempre falla", "Ambos tienen exactamente la misma velocidad y robustez"], "ok": 0, "fb": "Bisección se apoya en Bolzano (cambio de signo) y gana un bit por paso: infalible pero lenta. Newton sigue la tangente y casi duplica los dígitos por paso, pero puede dispararse si x₀ está lejos o f'(xₙ) ≈ 0." },
    { "q": "¿Qué condición vuelve peligrosa una iteración de Newton xₙ₊₁ = xₙ − f(xₙ)/f'(xₙ)?", "opts": ["Que f'(xₙ) sea cero o casi cero: la tangente casi horizontal dispara la aproximación lejos", "Que f(xₙ) sea negativa", "Que el intervalo inicial sea muy grande, sin importar f'"], "ok": 0, "fb": "Si f'(xₙ) ≈ 0 la tangente es casi horizontal y corta el eje x lejísimos, alejando la aproximación de la raíz (o dejando la fórmula indefinida si f' = 0). Por eso la elección de x₀ y el control del error son el corazón del método." },
    { "q": "Una IA resolvió x² − 2 = 0 por Newton desde x₁ = 1 y reportó: «f(1) = −1, f'(1) = 2, x₂ = 1 − (−1)/2 = 1,5». ¿Es válida?", "opts": ["Sí: el doble signo negativo suma, x₂ = 1,5, que está más cerca de √2 ≈ 1,4142, y f'(1) = 2 ≠ 0", "No, porque −(−1)/2 da −0,5 y x₂ debería ser 0,5", "No, porque Newton no sirve para raíces cuadradas"], "ok": 0, "fb": "Correcto: f'(x) = 2x, f(1) = −1, y −(−1)/2 = +0,5, así que x₂ = 1,5, más cerca de √2 que x₁. Auditar también es confirmar lo correcto y verificar la condición de validez f'(x₁) = 2 ≠ 0." }
  ]
},
"24": {
  "titulo": "¿Por qué el mismo idioma sirve para mundos tan distintos?",
  "qs": [
    { "q": "¿Cuál es la estructura común que une la caída de Galileo, el costo marginal, la población y la tomografía?", "opts": ["Una cantidad que cambia (derivada) y una que se acumula (integral), ligadas por el TFC: Q(b) − Q(a) = ∫ₐᵇ q(t) dt", "Que todos los fenómenos se describen con la misma fórmula numérica", "Que solo la física se puede modelar con cálculo"], "ok": 0, "fb": "En todos hay una tasa (derivada) y una cantidad acumulada (integral), y son dos caras del mismo fenómeno por el TFC. Distinto vocabulario por disciplina, misma estructura: velocidad↔posición, marginal↔total, tasa de crecimiento↔población." },
    { "q": "Según la clase, ¿cuál es la respuesta a la pregunta del año?", "opts": ["Cambiar y acumular son la misma pregunta al revés porque derivar e integrar son inversas, y el TFC es la bisagra", "Son dos temas independientes que se estudian por separado", "El cálculo solo describe fenómenos donde nada cambia de signo"], "ok": 0, "fb": "Medir cómo algo cambia y cuánto se acumula son la misma cuestión invertida: derivar y acumular son operaciones inversas, unidas por el Teorema Fundamental del Cálculo. Ese es el cierre del año." },
    { "q": "En el modelo logístico dP/dt = k·P·(1 − P/M), ¿qué representa M y qué pasa a largo plazo?", "opts": ["M es la capacidad de carga: si 0 < P < M la población crece y se aproxima a M, el equilibrio estable", "M es la población inicial, que nunca cambia", "M es la velocidad de crecimiento, que se mantiene constante"], "ok": 0, "fb": "M es la capacidad de carga. Los equilibrios (dP/dt = 0) son P = 0 y P = M; con P entre ambos la tasa es positiva, la población crece y tiende a M. Es crecimiento limitado por el entorno." },
    { "q": "Una IA modeló dP/dt = 0,5·P·(1 − P/1000), P(0) = 100, y dijo: «P tiende a 1000 porque los factores con resta siempre tienden a cero». ¿Es válida?", "opts": ["No: la conclusión P → 1000 es correcta, pero «los factores con resta tienden a cero» es una regla inventada", "Sí, el razonamiento sobre factores con resta es correcto", "No, porque P en realidad tiende a 0"], "ok": 0, "fb": "El resultado está bien pero la justificación es inválida (regla inventada). Lo correcto es analizar equilibrios: dP/dt = 0 en P = 0 y P = 1000; como P(0) = 100 da dP/dt > 0, la población crece hacia M = 1000, el equilibrio estable. Misma respuesta, razonamiento a rechazar." }
  ]
}
};
